#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building index.ls -> index.js ..."
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.js
echo "minify index.js -> index.min.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "copy plotdb-ffmpeg-worker.js to dist ..."
# the worker calls X where is set to db.abort
# however db.abort is undefined. anyway we fallback X to a empty function if db.abort is not defined.
cat ffmpeg.js/plotdb-ffmpeg-worker.js | sed 's/db.abort/db.abort || (function(){})/' > dist/worker.js

echo "copy dist to web ..."
rm -rf web/static/assets/lib/@plotdb/ffmpeg/main/
mkdir -p web/static/assets/lib/@plotdb/ffmpeg/main/
cp -R dist/* web/static/assets/lib/@plotdb/ffmpeg/main/
